### ISSUE TITLE
Doesn't work when WP is in subfolder

### ISSUE THREAD

**Issue by cvladan** [qriouslad/database-admin#3]
Thank you for the effort with the plugin.
I just changed in IFRAME an URL and it worked so it's easy fix.

![image](https://github.com/qriouslad/database-admin/assets/1913156/b38b5333-a008-4bdd-8a02-bc3f26cbade2)

Btw, I don't know why, but it's still not on wp.org?

**Comment by qriouslad** [comment]
@cvladan thanks for reporting and suggesting the easy fix. This plugin was rejected from wp.org because there were already 2-3 other plugins using Adminer, though none are skinned properly in my opinion. Could not argue may way into approval, so, it lives on Github for now.
